### ISSUE TITLE
Prefer "-Dsbt.version=0.13.13" to avoid sbt version issues

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom.github.io#56]
When running `sbt new lagom/lagom-scala.g8` a version `0.13.13+` of the local sbt launcher is required. This implies we must tell users to upgrade.

Alternatively we could suggest using the command `sbt new -Dsbt.version=0.13.13 lagom/lagom-scala.g8` (or `lagom-scala.g8`), that would also lift the need to bump the version of the user's sbt launcher.

**Comment by TimMoore** [comment]
I just wonder whether there are other differences in the launcher script that we're not aware of.

The script repo is here: https://github.com/sbt/sbt-launcher-package/commits/master
It looks like it changes frequently, and unfortunately the repository hasn't been tagged consistently so it's hard to know what version each change first appears in.

My concern is that people will run into bugs that have already been fixed, and we might end up sinking a lot of time into trying to reproduce them before realizing that the problem is caused by an older launch script.

So my vote is to tell users how to check the version and upgrade if necessary.

**Comment by rstento** [comment]
@TimMoore, we do have the more detailed instructions that tell people how to check the version. (https://www.lagomframework.com/documentation/1.3.x/java/JavaPrereqs.html and https://www.lagomframework.com/documentation/1.3.x/scala/Installation.html) Unfortunately, during the usability tests, even users who visited those pages skipped the step for verifying the version. I think that we've done all we could reasonably do at this point to help new users be successful. But, as you point out, things can always change in dependencies outside of our control. But, I think this issue can be closed now.

thanks!

**Comment by TimMoore** [comment]
OK thanks for the comment. This sounds like a good compromise then.
